-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."TripTuner_amenity"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TripTuner_amenity_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_amenity_hotelRoom_id"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amenity_id bigint NOT NULL,
    hotelroom_id bigint NOT NULL,
    CONSTRAINT "TripTuner_amenity_hotelRoom_id_pkey" PRIMARY KEY (id),
    CONSTRAINT "TripTuner_amenity_hotelR_amenity_id_hotelroomimag_ed62ba85_uniq" UNIQUE (amenity_id, hotelroom_id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_city"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country_id_id bigint,
    CONSTRAINT "TripTuner_city_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_country"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TripTuner_country_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_flight"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    flight_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    amount_places integer NOT NULL,
    "VISA" boolean NOT NULL,
    cost_with_bag numeric(10, 2) NOT NULL,
    cost_without_bag numeric(10, 2) NOT NULL,
    way numeric(10, 2) NOT NULL,
    days_of_rest integer NOT NULL,
    return_date timestamp with time zone NOT NULL,
    departure_date timestamp with time zone NOT NULL,
    arrival_location_id_id bigint NOT NULL,
    departure_location_id_id bigint NOT NULL,
    tour_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_flight_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_flighthotelhotelroom"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    flight_id_id bigint NOT NULL,
    "hotelRoom_id_id" bigint NOT NULL,
    hotel_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_flighthotelhotelroom_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_hotel"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    city_id_id bigint,
    CONSTRAINT "TripTuner_hotel_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_hotelroom"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    size numeric(10, 2) NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    hotel_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_hotelroom_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_hotelroomimage"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "hotelRoom_id_id" bigint NOT NULL,
    CONSTRAINT "TripTuner_hotelroomimage_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_order"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    booking_place integer NOT NULL,
    price_of_order numeric(10, 2) NOT NULL,
    date_ordered timestamp with time zone NOT NULL,
    flight_id_id bigint NOT NULL,
    client_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_order_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_orderhistory"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    order_id_id bigint NOT NULL,
    client_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_orderhistory_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_payment"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    payment_amount numeric(10, 2) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    payment_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default" NOT NULL,
    order_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_payment_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_review"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rating integer,
    advantages text COLLATE pg_catalog."default",
    disadvantages text COLLATE pg_catalog."default",
    review_date timestamp with time zone NOT NULL,
    "hotelRoom_id_id" bigint,
    client_id_id bigint NOT NULL,
    CONSTRAINT "TripTuner_review_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_supportticket"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    issue_description text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    answer_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    client_id_id bigint NOT NULL,
    "tourAgent_id_id" bigint,
    CONSTRAINT "TripTuner_supportticket_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_tour"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    image character varying(100) COLLATE pg_catalog."default" NOT NULL,
    title character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    country_id_id bigint,
    CONSTRAINT "TripTuner_tour_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_tour_tourAgent_id"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tour_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT "TripTuner_tour_tourAgent_id_pkey" PRIMARY KEY (id),
    CONSTRAINT "TripTuner_tour_tourAgent_id_tour_id_user_id_a58e8e14_uniq" UNIQUE (tour_id, user_id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_user"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image character varying(100) COLLATE pg_catalog."default",
    email character varying(50) COLLATE pg_catalog."default",
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    patronymic character varying(50) COLLATE pg_catalog."default",
    phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "TripTuner_user_pkey" PRIMARY KEY (id),
    CONSTRAINT "TripTuner_user_email_key" UNIQUE (email),
    CONSTRAINT "TripTuner_user_username_key" UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_user_groups"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT "TripTuner_user_groups_pkey" PRIMARY KEY (id),
    CONSTRAINT "TripTuner_user_groups_user_id_group_id_2a840455_uniq" UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public."TripTuner_user_user_permissions"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT "TripTuner_user_user_permissions_pkey" PRIMARY KEY (id),
    CONSTRAINT "TripTuner_user_user_perm_user_id_permission_id_f1356656_uniq" UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

ALTER TABLE IF EXISTS public."TripTuner_amenity_hotelRoom_id"
    ADD CONSTRAINT "TripTuner_amenity_ho_amenity_id_f58613a2_fk_TripTuner" FOREIGN KEY (amenity_id)
    REFERENCES public."TripTuner_amenity" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_amenity_hotelRoom_id_amenity_id_f58613a2"
    ON public."TripTuner_amenity_hotelRoom_id"(amenity_id);


ALTER TABLE IF EXISTS public."TripTuner_amenity_hotelRoom_id"
    ADD CONSTRAINT "TripTuner_amenity_ho_hotelroom_id_96865713_fk_TripTuner" FOREIGN KEY (hotelroom_id)
    REFERENCES public."TripTuner_hotelroom" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_amenity_hotelRoom_id_hotelroomimage_id_7febac15"
    ON public."TripTuner_amenity_hotelRoom_id"(hotelroom_id);


ALTER TABLE IF EXISTS public."TripTuner_city"
    ADD CONSTRAINT "TripTuner_city_country_id_id_42aadeff_fk_TripTuner_country_id" FOREIGN KEY (country_id_id)
    REFERENCES public."TripTuner_country" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_city_country_id_id_42aadeff"
    ON public."TripTuner_city"(country_id_id);


ALTER TABLE IF EXISTS public."TripTuner_flight"
    ADD CONSTRAINT "TripTuner_flight_arrival_location_id__5c798a0a_fk_TripTuner" FOREIGN KEY (arrival_location_id_id)
    REFERENCES public."TripTuner_city" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flight_arrival_location_id_id_5c798a0a"
    ON public."TripTuner_flight"(arrival_location_id_id);


ALTER TABLE IF EXISTS public."TripTuner_flight"
    ADD CONSTRAINT "TripTuner_flight_departure_location_i_3bc24639_fk_TripTuner" FOREIGN KEY (departure_location_id_id)
    REFERENCES public."TripTuner_city" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flight_departure_location_id_id_3bc24639"
    ON public."TripTuner_flight"(departure_location_id_id);


ALTER TABLE IF EXISTS public."TripTuner_flight"
    ADD CONSTRAINT "TripTuner_flight_tour_id_id_e168bd20_fk_TripTuner_tour_id" FOREIGN KEY (tour_id_id)
    REFERENCES public."TripTuner_tour" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flight_tour_id_id_e168bd20"
    ON public."TripTuner_flight"(tour_id_id);


ALTER TABLE IF EXISTS public."TripTuner_flighthotelhotelroom"
    ADD CONSTRAINT "TripTuner_flighthote_flight_id_id_4547ca1e_fk_TripTuner" FOREIGN KEY (flight_id_id)
    REFERENCES public."TripTuner_flight" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flighthotelhotelroom_flight_id_id_4547ca1e"
    ON public."TripTuner_flighthotelhotelroom"(flight_id_id);


ALTER TABLE IF EXISTS public."TripTuner_flighthotelhotelroom"
    ADD CONSTRAINT "TripTuner_flighthote_hotelRoom_id_id_ebebd34a_fk_TripTuner" FOREIGN KEY ("hotelRoom_id_id")
    REFERENCES public."TripTuner_hotelroom" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flighthotelhotelroom_hotelRoom_id_id_ebebd34a"
    ON public."TripTuner_flighthotelhotelroom"("hotelRoom_id_id");


ALTER TABLE IF EXISTS public."TripTuner_flighthotelhotelroom"
    ADD CONSTRAINT "TripTuner_flighthote_hotel_id_id_bb672eb3_fk_TripTuner" FOREIGN KEY (hotel_id_id)
    REFERENCES public."TripTuner_hotel" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_flighthotelhotelroom_hotel_id_id_bb672eb3"
    ON public."TripTuner_flighthotelhotelroom"(hotel_id_id);


ALTER TABLE IF EXISTS public."TripTuner_hotel"
    ADD CONSTRAINT "TripTuner_hotel_city_id_id_8a406af4_fk_TripTuner_city_id" FOREIGN KEY (city_id_id)
    REFERENCES public."TripTuner_city" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_hotel_city_id_id_8a406af4"
    ON public."TripTuner_hotel"(city_id_id);


ALTER TABLE IF EXISTS public."TripTuner_hotelroom"
    ADD CONSTRAINT "TripTuner_hotelroom_hotel_id_id_4ed41039_fk_TripTuner_hotel_id" FOREIGN KEY (hotel_id_id)
    REFERENCES public."TripTuner_hotel" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_hotelroom_hotel_id_id_4ed41039"
    ON public."TripTuner_hotelroom"(hotel_id_id);


ALTER TABLE IF EXISTS public."TripTuner_hotelroomimage"
    ADD CONSTRAINT "TripTuner_hotelroomi_hotelRoom_id_id_50a9bc47_fk_TripTuner" FOREIGN KEY ("hotelRoom_id_id")
    REFERENCES public."TripTuner_hotelroom" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_hotelroomimage_hotelRoom_id_id_50a9bc47"
    ON public."TripTuner_hotelroomimage"("hotelRoom_id_id");


ALTER TABLE IF EXISTS public."TripTuner_order"
    ADD CONSTRAINT "TripTuner_order_client_id_id_92d9302a_fk_TripTuner_user_id" FOREIGN KEY (client_id_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_order_client_id_id_92d9302a"
    ON public."TripTuner_order"(client_id_id);


ALTER TABLE IF EXISTS public."TripTuner_order"
    ADD CONSTRAINT "TripTuner_order_flight_id_id_03f55e98_fk_TripTuner_flight_id" FOREIGN KEY (flight_id_id)
    REFERENCES public."TripTuner_flight" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_order_flight_id_id_03f55e98"
    ON public."TripTuner_order"(flight_id_id);


ALTER TABLE IF EXISTS public."TripTuner_orderhistory"
    ADD CONSTRAINT "TripTuner_orderhisto_client_id_id_88cdf2f5_fk_TripTuner" FOREIGN KEY (client_id_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_orderhistory_client_id_id_88cdf2f5"
    ON public."TripTuner_orderhistory"(client_id_id);


ALTER TABLE IF EXISTS public."TripTuner_orderhistory"
    ADD CONSTRAINT "TripTuner_orderhisto_order_id_id_4eacad38_fk_TripTuner" FOREIGN KEY (order_id_id)
    REFERENCES public."TripTuner_order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_orderhistory_order_id_id_4eacad38"
    ON public."TripTuner_orderhistory"(order_id_id);


ALTER TABLE IF EXISTS public."TripTuner_payment"
    ADD CONSTRAINT "TripTuner_payment_order_id_id_4ac86941_fk_TripTuner_order_id" FOREIGN KEY (order_id_id)
    REFERENCES public."TripTuner_order" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_payment_order_id_id_4ac86941"
    ON public."TripTuner_payment"(order_id_id);


ALTER TABLE IF EXISTS public."TripTuner_review"
    ADD CONSTRAINT "TripTuner_review_client_id_id_958ff358_fk_TripTuner_user_id" FOREIGN KEY (client_id_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_review_client_id_id_958ff358"
    ON public."TripTuner_review"(client_id_id);


ALTER TABLE IF EXISTS public."TripTuner_review"
    ADD CONSTRAINT "TripTuner_review_hotelRoom_id_id_00db0756_fk_TripTuner" FOREIGN KEY ("hotelRoom_id_id")
    REFERENCES public."TripTuner_hotelroom" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_review_hotelRoom_id_id_00db0756"
    ON public."TripTuner_review"("hotelRoom_id_id");


ALTER TABLE IF EXISTS public."TripTuner_supportticket"
    ADD CONSTRAINT "TripTuner_supporttic_client_id_id_7cd2f445_fk_TripTuner" FOREIGN KEY (client_id_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_supportticket_client_id_id_7cd2f445"
    ON public."TripTuner_supportticket"(client_id_id);


ALTER TABLE IF EXISTS public."TripTuner_supportticket"
    ADD CONSTRAINT "TripTuner_supporttic_tourAgent_id_id_9f938259_fk_TripTuner" FOREIGN KEY ("tourAgent_id_id")
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_supportticket_tourAgent_id_id_9f938259"
    ON public."TripTuner_supportticket"("tourAgent_id_id");


ALTER TABLE IF EXISTS public."TripTuner_tour"
    ADD CONSTRAINT "TripTuner_tour_country_id_id_4373e80f_fk_TripTuner_country_id" FOREIGN KEY (country_id_id)
    REFERENCES public."TripTuner_country" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_tour_country_id_id_4373e80f"
    ON public."TripTuner_tour"(country_id_id);


ALTER TABLE IF EXISTS public."TripTuner_tour_tourAgent_id"
    ADD CONSTRAINT "TripTuner_tour_tourA_tour_id_7ae3d3a3_fk_TripTuner" FOREIGN KEY (tour_id)
    REFERENCES public."TripTuner_tour" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_tour_tourAgent_id_tour_id_7ae3d3a3"
    ON public."TripTuner_tour_tourAgent_id"(tour_id);


ALTER TABLE IF EXISTS public."TripTuner_tour_tourAgent_id"
    ADD CONSTRAINT "TripTuner_tour_tourA_user_id_f8ede8bf_fk_TripTuner" FOREIGN KEY (user_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_tour_tourAgent_id_user_id_f8ede8bf"
    ON public."TripTuner_tour_tourAgent_id"(user_id);


ALTER TABLE IF EXISTS public."TripTuner_user_groups"
    ADD CONSTRAINT "TripTuner_user_groups_group_id_247b6dd5_fk_auth_group_id" FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_user_groups_group_id_247b6dd5"
    ON public."TripTuner_user_groups"(group_id);


ALTER TABLE IF EXISTS public."TripTuner_user_groups"
    ADD CONSTRAINT "TripTuner_user_groups_user_id_7ba3687f_fk_TripTuner_user_id" FOREIGN KEY (user_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_user_groups_user_id_7ba3687f"
    ON public."TripTuner_user_groups"(user_id);


ALTER TABLE IF EXISTS public."TripTuner_user_user_permissions"
    ADD CONSTRAINT "TripTuner_user_user__permission_id_08ff518c_fk_auth_perm" FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_user_user_permissions_permission_id_08ff518c"
    ON public."TripTuner_user_user_permissions"(permission_id);


ALTER TABLE IF EXISTS public."TripTuner_user_user_permissions"
    ADD CONSTRAINT "TripTuner_user_user__user_id_c1aa6517_fk_TripTuner" FOREIGN KEY (user_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS "TripTuner_user_user_permissions_user_id_c1aa6517"
    ON public."TripTuner_user_user_permissions"(user_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_TripTuner_user_id" FOREIGN KEY (user_id)
    REFERENCES public."TripTuner_user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);

END;