# Generated by Django 5.1.2 on 2024-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0002_alter_amenity_hotelroom_id_flighthotelhotelroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название комнаты'),
        ),
    ]
