# Generated by Django 5.1.2 on 2024-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0003_alter_hotel_name_alter_hotelroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=models.TextField(default=None, verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='review',
            name='disadvantages',
            field=models.TextField(default=None, verbose_name='Недостатки'),
        ),
    ]
