# Generated by Django 5.1.2 on 2024-11-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0004_alter_review_advantages_alter_review_disadvantages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='VISA',
            field=models.BooleanField(default=False, verbose_name='Нужна виза?'),
        ),
    ]
