# Generated by Django 5.1.2 on 2024-11-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0005_alter_flight_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure_date_back',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='return_date_back',
        ),
    ]
