# Generated by Django 5.1.2 on 2024-11-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0007_alter_supportticket_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TripTuner.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TripTuner.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='city_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TripTuner.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='review',
            name='disadvantages',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Недостатки'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotelRoom_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TripTuner.hotelroom', verbose_name='Номер отеля'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='tourAgent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Турагент'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='TripTuner.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourAgent_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Турагент'),
        ),
    ]
