# Generated by Django 5.1.2 on 2024-11-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landmark',
        ),
    ]
