# Generated by Django 5.1.2 on 2024-11-17 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripTuner', '0011_alter_tour_touragent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tourAgent_id',
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL, verbose_name='Турагент'),
        ),
    ]
